name: release-please

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release-please:
    uses: mauhlik/reusable-workflows/.github/workflows/release-please.yml@v1
    with:
      environment: default
      config-file: .github/release-please/release-please-config.json
      manifest-file: .github/release-please/.release-please-manifest.json
    secrets: inherit