name: Update tags
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tags:
    uses: mauhlik/reusable-workflows/.github/workflows/update-tags.yml@v1